### PR TITLE
ALV2 Surjectivity of functors

### PR DESCRIPTION
**Pull request by fizruk**
TODO:

- [x] show that a functor from relu(J) to wkrelu(J) is surjective (assuming AC and set-category C)
- [x] show that a functor from relu(J) to relu(J') is surjective under some conditions?
- [x] apply the proofs to the diagram with Yoneda embeddings
- [ ] give counterexamples for non-set categories C?

### CODE REVIEW

**Comment by fizruk** [comment]
I have some progress, but the proof is a bit long already, so I am taking a break.
Since the code is not exactly readable at this moment, below is description of my progress.

In order to show that a functor from relu(J) to relu(J') is surjective we can easily get a preimage of the morphism in D'. However, it seems that it is not straightforward to get a preimage of the pullback. We have the following picture in relative universes:

Screenshot 2020-03-10 at 01 37 47

S should be an equivalence to allow easy preimage of the morphism in D'. Keeping in mind that later both J and J' will be Yoneda embeddings, we can assume that J and J' are equivalences as well (if needed). We cannot assume R to be an equivalence since it will be instantiated by Rezk completion.

Screenshot 2020-03-10 at 01 30 06

A relative J'-universe will provide us (for any X and f) an object in C' as well as a morphism in C'. Specifically, to construct pullback for the relative J-universe we will have the following data:

Screenshot 2020-03-10 at 01 32 22

To get an object in C from an object in C' we can use the fact that R is (split) essentially surjective. However, for morphisms we will need to find a roundabout way: via J' to D', then via inverse S to D, then via inverse J to C.

Screenshot 2020-03-10 at 01 35 33

Finally we can obtain the necessary map in C and pullback data as follows:

Screenshot 2020-03-10 at 01 35 50

<details>
  <summary>LaTeX code for the diagrams</summary>

```latex
\[
  \xymatrix{
           \C \drtwocell<\omit>{\alpha} \ar[r]^{J} \ar[d]_{R}& \D \ar[d]^{S}\\
           \C' \ar[r]_{J'} & \D',
  }
\]

\begin{itemize}
\item $J$ and $J'$ are fully faithful,
\item $J$ is an equivalence,
\item $\D$ and $\D'$ are both univalent,
\item $S$ is an equivalence, and
\item $R$ is (split) essentially surjective,
\end{itemize}

Given a $J'$-relative universe we have

\begin{enumerate}
  \item $p : \tU \to U$ --- a morphism in $\D'$;
  \item for any object $X : \C$ and a morphism $f : J(X) \to S^{-1}(U)$ in $\D$ we have
    \begin{enumerate}
      \item an object $X.f_\C' : \C'$,
      \item a morphism $p' : X.f_\C' \to R(X)$ and
      \item a morphism $Q : J'(X.f_\C') \to \tU$
      \item such that the following square commutes and is a pullback
        \[
          \xymatrix{
                **[l] J(X.f_\C') \ar[r]^-{Q} \ar[d]_{J(p')} \pb & \tU \ar[d]^{\p}\\
                **[l] JR(X) \ar[r]_{Sf}& \U
                }
        \]
    \end{enumerate}
\end{enumerate}

Let us denote $X.f_\C = J^{-1}S^{-1}J'(X.f_\C')$.
Then we can obtain relative $J$-universe as follows:

\[
   \xymatrix@C=2pc{
       X.f_\C \ar@{<->}[d]^-{\simeq}
     & J(X.f_\C) = S^{-1}J'(R(X.f_\C)) \ar@{<->}[r]^-{\simeq} \ar@{<->}[d]^-{\simeq} \pb
     & S^{-1}J'(X.f_{\C'}) \ar@{->}[r]^-{S^{-1}Q(RX,Sf)}
     & S^{-1}\tU \ar@{->}[dddd]^-{S^{-1}p} \\
   J^{-1}S^{-1}J'R(X.f_\C) \ar@{<->}[d]^-{\simeq} &
  JJ^{-1}S^{-1}J'R(X.f_\C) \ar@{<->}[d]^-{\simeq} & & \\
   J^{-1}S^{-1}J'(X.f_\C') \ar[d]^-{J^{-1}S^{-1}J'p'} &
  JJ^{-1}S^{-1}J'(X.f_\C') \ar[d]^-{J^{-1}S^{-1}J'p'} & & \\
   J^{-1}S^{-1}J'R(X) \ar@{<->}[d]^-{\simeq}  &
  JJ^{-1}S^{-1}J'R(X) \ar@{<->}[d]^-{\simeq} & & \\
  X & JX \ar[rr]^-{f} & & S^{-1}U
   }
\]
```
</details>

**Comment by benediktahrens** [comment]
These assumptions are too strong: J is not an equivalence, but only fully faithful (an equivalence on morphisms) in the case we are interested in (J = Yoneda embedding). In that case, J is not even surjective (split or not).

I'll think about it in the next days.

**Comment by fizruk** [comment]
@benediktahrens I think we don't have to. I realised that I can avoid direct proof and rely instead on the commutative square from #166. We already know two sides of that square to be `catiso` and the third one is proven surjective.

I completed the proof of surjectivity using this idea and applied it to the case of Yoneda.
If you are happy with this approach, I think it is ready for merge 😊 

---

P. S. Note that in the attempt to prove directly I proved this helper (a similar one with precompose exists already), which I removed it from this PR, but let me know if it should be submitted somewhere (e.g. `Auxiliary`):

https://github.com/UniMath/TypeTheory/blob/5bdfb0e691925f1c10d865044461fdc225c862be/TypeTheory/ALV2/RelUnivTransfer.v#L336-L384

**Comment by benediktahrens** [comment]
That's amazing, bravo!

Regarding your ps: yes, this construction would be good to have! How 
about putting it in UniMath/UniMath? The file CategoryTheory/catiso.v 
could be a good place for it.

**Pull request merged**
