### PR TITLE
WIP: restore compilation after merge of PR #1507 of UniMath

### PR DESCRIPTION
**Pull request by rmatthes**
currently over half of the files compile

### CODE REVIEW

**Comment by benediktahrens** [comment]
How does this compare to https://github.com/UniMath/TypeTheory/pull/216 ?

**Comment by rmatthes** [comment]
I counted on being notified of developments by GitHub, but I now see I ought to have made changes to the settings for that. So bad. Probably, both PR propose similar changes to the same files.

**Comment by rmatthes** [comment]
What I did more than PR #216 : 
- no commenting out of code in [TypeTheory/Auxiliary/DisplayedCategories.v](https://github.com/UniMath/TypeTheory/pull/218/files#diff-e61da8d5f7d1fd2878add323f034cbf6225dd199cc99960fca043632304ac408) - surprisingly easy remedy in that part
- [TypeTheory/CwF/CwF_def.v](https://github.com/UniMath/TypeTheory/pull/218/files#diff-b88958cce9ba23316531565e9e50473914d2efd3212921a5d2f50a2ed1b59e88)
- [TypeTheory/RelUniv/RelUnivTransfer.v](https://github.com/UniMath/TypeTheory/pull/218/files#diff-c211849369ad30db17ea0a75469ba5644e72311fa458006e2e1f4456d4ba52cf) - I struggled a bit with this one
- [TypeTheory/RelUniv/Transport_along_Equivs.v](https://github.com/UniMath/TypeTheory/pull/218/files#diff-8ffd68e09c3a4dc5ac0a927e5a9c1198b772ff1d31d826eb884e43e2d082104e)

**Comment by rmatthes** [comment]
I have put the modifications in the above-mentioned files on top of PR #216 (together with their dependencies), this became PR #219.

The present PR should be closed as soon as the remaining files have been compared with those in PR #216.

**Comment by rmatthes** [comment]
Comparison completed.

**Pull request closed without merging**
