### PR TITLE
adapted to pointless change in unimath

### PR DESCRIPTION
**Pull request by benediktahrens**

### CODE REVIEW

**Comment by DanGrayson** [comment]
Well, we have to use the right symbols that the inventors of unicode have provided to us, so it's not so pointless as all that. :-)

**Comment by benediktahrens** [comment]
On 02/03/2017 01:52 PM, Daniel R. Grayson wrote:
> Well, we have to use the right symbols that the inventors of unicode
> have provided to us, so it's not so pointless as all that. :-)

You are not the free spirit I thought you were.

The new symbols are aesthetically less pleasing than the old ones,
unfortunately.

To me the main purpose of this change seems to be to teach me about
dired. Goal achieved!

**Comment by DanGrayson** [comment]
dired?  I think the main goal was to teach you about this:
```
M-R runs the command tags-query-replace (found in global-map), which is an
interactive autoloaded compiled Lisp function in ‘etags.el’.

It is bound to M-R, <menu-bar> <edit> <replace> <tags-repl>.

(tags-query-replace FROM TO &optional DELIMITED FILE-LIST-FORM)

Do ‘query-replace-regexp’ of FROM with TO on all files listed in tags table.
Third arg DELIMITED (prefix arg) means replace only word-delimited matches.
If you exit (C-g, RET or q), you can resume the query replace
with the command M-,.
Fourth arg FILE-LIST-FORM non-nil means initialize the replacement loop.

If FILE-LIST-FORM is non-nil, it is a form to evaluate to
produce the list of files to search.

See also the documentation of the variable ‘tags-file-name’.
```

**Comment by DanGrayson** [comment]
Re: "The new symbols are aesthetically less pleasing than the old ones, unfortunately."

What that means is that you've chosen an ugly font to display those symbols in.  Unicode itself contains no font information.

**Comment by DanGrayson** [comment]
Re: "You are not the free spirit I thought you were."

Gee, our whole project is about making mathematics rigorously correct, so I get to let my instinct for tidiness have free rein.

**Comment by benediktahrens** [comment]
Mmh, next time then. This time I solved the task without TAGS.
Looking forward to the next renaming ;-)

**Pull request merged**
