### PR TITLE
a try to provide a one-parameter induction principle

### PR DESCRIPTION
**Pull request by rmatthes**
for the isover relation on towers

should be the induction principle according to Lemma 2.2 of http://www.tac.mta.ca/tac/volumes/31/36/31-36.pdf by Vladimir Voevodsky
Problems: proof only works for towers in hSet
          proof incomplete due to a problem of dependent rewriting - help needed

In this sense, this is not really a pull request but a request for comments.

### CODE REVIEW

**Comment by rmatthes** [comment]
Unfortunately, I see hardly any places in the code provided under PR #117 that would alternatively be able to make use of the suggested induction principle. For example, ftn_S and ftn_T in S_St.v and T_Tt.v, respectively, would lose in precision if only the relation isover was concluded.

**Comment by rmatthes** [comment]
@vladimirias : Is there a reason why names of systems in the B family are often described with lB in the name? This concerns the names of ten vernacular files but is also used in definitions and comments.

**Comment by vladimirias** [comment]
Yes. There are two approaches to the definition of B-system carriers either as two families of types parametrized by natural numbers (one for B and one for \tilde{B}) or as two types B and Bt with the length function l:B -> nat that defines a length function on Bt by composition with partial : Bt -> B. To distinguish the two the first structure is called in formalization a B-system and the second an lB-system. The current formalization is using lB-approach since it turned out to be more convenient to use a single type B and a function l:B->nat than to use a family of dependent types B n.

**Comment by rmatthes** [comment]
@vladimirias : Thank you, I ought to have guessed the meaning of l. I just went through the doc of the files and tried to make this naming even more visible (at a few places).

**Comment by rmatthes** [comment]
I have separated this PR into PR #120 concerning most of the commits here and a future PR just about the induction principle.

So, this PR should be on hold.

**Pull request merged**
