### PR TITLE
first steps to make TypeTheory compatible with Coq 8.16

### PR DESCRIPTION
**Pull request by benediktahrens**
relates to #230 

@m-lindgren observed that TypeTheory is not currently compatible with Coq 8.16. One culprit seems to be the notations introduced to work with presheaves. I leave here the traces of my experiments, which do not provide a principled or complete solution. Has the handling of notations changed between 8.15.2 and 8.16?

@peterlefanulumsdaine @mortberg : would you have some time to look into this?

### CODE REVIEW

**Comment by benediktahrens** [comment]
It would be fantastic if we could somehow add TypeTheory to Coq's CI...

**Comment by peterlefanulumsdaine** [comment]
Thanks @m-lindgren for raising this!  I’ll definitely to try take a look at it, but I’m a bit busy over the next few weeks, so I don’t know how soon I’ll manage to get to it.

**Comment by m-lindgren** [comment]
I believe the issue is related to Coq [removing](https://github.com/coq/coq/pull/15789)  the uniform inheritance condition for coercions, causing coercions that previously wouldn't trigger to do so. In suspect that `yy` only having implicit arguments caused some problems.

By using `Set Printing Implicit` and switching back and forth between 8.15 and 8.16 (opam switches are great for this) I managed to get the library to at least compile, but I think the fixes can be improved a bit.

**Comment by m-lindgren** [comment]
I'll mark this ready for review. The changes made are pretty straight forward, it's mostly just changing calls of `yy` to `@yy _ _ _`.

This also includes changes to the CI to build TypeTheory using Coq `8.15`, `8.16` and the latest available release.

**Comment by benediktahrens** [comment]
Somehow I had forgotten about this PR. @m-lindgren @peterlefanulumsdaine do you agree with merging this?

**Comment by m-lindgren** [comment]
I'm fine with merging this. It would allow us to compile typetheory with 8.16 in UniMath, and also see if it compiles with coq-dev. I'm pretty sure there are no non-trivial changes in this PR, but not entirely sure, so I added Peter as a reviewer.

**Comment by benediktahrens** [comment]
I suggest we merge this now, even without @peterlefanulumsdaine's review. @peterlefanulumsdaine can still comment later.

**Pull request merged**
