### PR TITLE
make Vladimir Voevodsky's implementation of B-systems available in TypeTheory

### PR DESCRIPTION
**Pull request by rmatthes**
all the vernacular files are the work of VV, I only worked on the inclusion paths and made a small change to ensure that the files compile well

### CODE REVIEW

**Comment by benediktahrens** [comment]
lgtm. obviously, there is a lot of work to be done on these files, but that'll take some time and should be done iteratively.

**Comment by rmatthes** [comment]
I am working on commenting the files and providing help with mapping the contents to the publications. I would be glad to take into account a successor to the Oct. 2014 version of the paper on B-systems.

**Comment by vladimirias** [comment]
One modification that I would like to see done is to replace all uses of induction on nat by the use of the dependent type version of the induction principle expressed in Lemma 2.2 in http://www.tac.mta.ca/tac/volumes/31/36/31-36.pdf <http://www.tac.mta.ca/tac/volumes/31/36/31-36.pdf> . This induction principle is defined for any lft-set, but it is more general being available also, for example, for the analog of lft-sets where l takes values in integers.

**Comment by benediktahrens** [comment]
Merging, the TODOs should be addressed in a future PR.

**Pull request merged**
