### PR TITLE
update import statements to make the package compile

### PR DESCRIPTION
**Pull request by rmatthes**
take into account the restructuring of the UniMath library

### CODE REVIEW

**Comment by benediktahrens** [comment]
I think there is CategoryTheory.Core.Prelude which brings in all the other stuff from Core.

**Comment by benediktahrens** [comment]
Thanks for fixing this!

**Comment by rmatthes** [comment]
Okay, I now use Prelude once (and keep importing less in the other files).

**Comment by rmatthes** [comment]
Is there an ongoing Travis check? I suspect that this is not the case.

**Pull request merged**
