### PR TITLE
try to prove that C-systems have pullback diagrams for q

### PR DESCRIPTION
**Pull request by rmatthes**
This tries to formalize a proposition in the first C-systems paper by VV.

Currently, I am struggling with showing that g can be calculated from its father and its composition with q. The part that is shown on paper is already fine, but there is a subtle type dependency that I do not get rid of.

Not yet a real PR.

### CODE REVIEW

**Comment by rmatthes** [comment]
I have the lemma now, but the proof is currently terribly ugly, which is why I do not commit it.

**Comment by benediktahrens** [comment]
If you commit and push, there is some hope you get help improving it. If 
you don't, there isn't.

**Comment by rmatthes** [comment]
I really felt I should clean up the proof a bit before you look at it. There is still room for optimization.

**Comment by rmatthes** [comment]
This mini-project is accomplished. Feedback most welcome, towards pulling this development.

**Comment by rmatthes** [comment]
Thank you for the code review that concerned to a good extent the current rendering of the code originally due to Vladimir. I understand that `rewrite` should be avoided, but hundreds of occurrences stay there.

Does my proof of Proposition 2.4 of VV look particularly awkward or just as complicated as it needs to be in view of all these type-casts in combination with coercive subtyping?

**Comment by benediktahrens** [comment]
On 08/06/18 13:13, Ralph Matthes wrote:
> Thank you for the code review that concerned to a good extent the 
> current rendering of the code originally due to Vladimir. I understand 
> that |rewrite| should be avoided, but hundreds of occurrences stay there.
> 
> Does my proof of Proposition 2.4 of VV look particularly awkward or just 
> as complicated as it needs to be in view of all these type-casts in 
> combination with coercive subtyping?

I did not see any places with obvious room for improvement, but then I 
also have not understood the global structure of the proofs. Sorry....

**Comment by rmatthes** [comment]
The check failed due to a problem with the PPA - this has nothing to do with my commit.

**Pull request merged**
