### PR TITLE
make the library compile again

### PR DESCRIPTION
**Pull request by rmatthes**
after the migration of most of Displayed_Cats to UniMath

delete all the migrated files
for convenience: have a file to import all of those developments that are now in UniMath
adapt the files in ALV2 to refer to UniMath instead of the deleted files

### CODE REVIEW

**Comment by rmatthes** [comment]
I did not update any of the README parts.

**Comment by benediktahrens** [comment]
The build problem here comes from the Travis file: it lists the packages CategoryTheory and Topology in the wrong order, thus causing UniMath/UniMath make to fail in one of Grayson's checks.

The fix is as in my PR: https://github.com/UniMath/TypeTheory/pull/122/commits/07cdc9f2ea4ba8991092538d3be9df1059cb6522

**Comment by benediktahrens** [comment]
I believe (but I am not sure) that your file `DisplayedCatsUniMath.v` is only useful if you replace `Require Import` by `Require Export`.
Otherwise lgtm.

**Comment by rmatthes** [comment]
@benediktahrens : I meant the file to check that all was still available and to point readers to the file names. But, yes, importing that file would not have been useful. Thanks.

**Pull request merged**
